export const PROMPT_OPTION_CHALLENGE_ACCEPT = 'PROMPT_OPTION_CHALLENGE_ACCEPT';
export const PROMPT_OPTION_CHALLENGE_PASS = 'PROMPT_OPTION_CHALLENGE_PASS';

export type PROMPT_OPTION_VALUE =
  typeof PROMPT_OPTION_CHALLENGE_ACCEPT |
  typeof PROMPT_OPTION_CHALLENGE_PASS;
